### ISSUE TITLE
Quant data from MSstats output or Triqler 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#14]
@daichengxin I think the output of Quant  (Figure) it is better to be retrieve from one of the tsv outputs, MSStatsts or Triqler. The problem is that we want the `peptide_study_variable[X]` to be replaced by the proper name of the Sample. `peptide_study_variable[X]` is not really informative. 

![Screen Shot 2021-03-28 at 09 46 33](https://user-images.githubusercontent.com/52113/112747092-0b7f3e00-8fab-11eb-9b47-9dcd996af2f1.png)

What do you think @timosachsenberg

**Comment by timosachsenberg** [comment]
I think  this might not be related to the mzTab output because you have a similar challenge for the MSstats and Triqler output: you need to map the entry back to the sample / conditions.

**Comment by daichengxin** [comment]
![image](https://user-images.githubusercontent.com/37200167/112751362-35168480-9000-11eb-814a-30c61923bc5e.png)
![image](https://user-images.githubusercontent.com/37200167/112751360-3182fd80-9000-11eb-8f62-7baaf3d222b0.png)

This mapping should be possible. Should the sample be used as the column or the condition should be used as the column in the end? As far as this test data is concerned, there are a total of 12 technical replicates, with the same sample name and condition. It seems that using sample and condition as columns is not the best
