### ISSUE TITLE
Test results Spectra Tracking looks weird

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/pmultiqc#19]
http://bigbio.xyz/pmultiqc/shared-peptides-star-align-stricter-pep-protein-FDR.html

the first file has so much more peptides. Can you double-check that?

**Comment by daichengxin** [comment]
Thanks @jpfeuffer, I found the reasons, and it's running again

**Comment by daichengxin** [comment]
#21

**Comment by ypriverol** [comment]
@jpfeuffer can you review the report.

**Comment by jpfeuffer** [comment]
Yes, awesome! Did you figure out the differences in numbers? Did it make sense to you now? I think the numbers look reasonable. I think the only thing left would be some text in the help about what the columns mean exactly.
<img width="951" alt="Bildschirmfoto 2021-04-22 um 16 36 12" src="https://user-images.githubusercontent.com/8102638/115733106-de933080-a388-11eb-848c-69212143d84c.png">

Probably some other help texts could be added too, but the actual plots are great!

**Comment by ypriverol** [comment]
This is related with issue #22
