### ISSUE TITLE
Distribution of peptides per protein 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#2]
Short description: This is a bar chart displaying the percentage of protein identifications in the whole experiment according to the total number of peptides used to report the identification. Proteins supported by more peptide identifications can constitute more confident results.

![image](https://user-images.githubusercontent.com/52113/111085524-a5f17300-850f-11eb-96a0-f2c20083834f.png)

**Comment by daichengxin** [comment]
#11
