### ISSUE TITLE
The The number of peptides finally identified is inconsistent in mzTab and csv

### ISSUE THREAD

**Issue by daichengxin** [bigbio/pmultiqc#20]
In UPS1 report, the number of peptides in the Pipeline Result Statistics table is extracted from the mstats csv file, and the number of peptides in the Spectra Tracking table is extracted from the PSM information in the mzTab file. Why is there a difference?

![image](https://user-images.githubusercontent.com/37200167/113730813-ca192c00-972a-11eb-82ca-6d6b13a6fa20.png)
![image](https://user-images.githubusercontent.com/37200167/113730854-d3a29400-972a-11eb-8349-9d5fa39254d9.png)

**Comment by daichengxin** [comment]
#21

**Comment by ypriverol** [comment]
@timosachsenberg @ulianus it may be because in the csv are the quantified peptides (at least intensity for one condition), where in the mzTab we have all PSMs identified, probably for a lot of peptides not even one feature can be found?

**Comment by jpfeuffer** [comment]
In this case it becomes more, right?
Was targeted_only set to false? Then it is probably the matching between runs that finds a quantity for a Peptide which did not have an ID in this run.

**Comment by ypriverol** [comment]
> In this case it becomes more, right?

The mzTab ones should be higher than the msstats output (as we are getting now) right?
 
> Was targeted_only set to false? Then it is probably the matching between runs that finds a quantity for a Peptide which did not have an ID in this run.

I think is the way around mzTab > msstats

**Comment by jpfeuffer** [comment]
which msstats csv file? the one from proteomicslfq as input for MSstats or the one after processing with MSstats?

**Comment by jpfeuffer** [comment]
If it is the second, then Yasset is right. If it is the first, they should be equal. But also there is also aggregation happening for best feature across fractions etc.
I need more information on which peptides/features go "missing" to give an exact answer.

**Comment by ypriverol** [comment]
> which msstats csv file? the one from proteomicslfq as input for MSstats (out_msstats.csv) or the one after processing with MSstats (msstats_results.csv)?

The input to MSStats

**Comment by jpfeuffer** [comment]
Are you counting decoy peptides??

**Comment by jpfeuffer** [comment]
Also MSstats only gets the PEP section, not the PSM section

**Comment by daichengxin** [comment]
I separately calculated the difference between the pep and psm section of mzTab and the peptide identified in out_msstats. It looks a little strange. The out_msstats sheet shows the peptides that appear in out_msstats, but not in the psm or pep section. 
https://docs.google.com/spreadsheets/d/1vwBD--OUx2DJVgsHA-564SghOdhUlUHO-5_sFbVj4pY/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1xzPblmtsB1FuUV4PMt8okhEFG6Q9ltZRALPZAh_4U_M/edit?usp=sharing

**Comment by jpfeuffer** [comment]
I unfortunately do not have access to the docs.

**Comment by daichengxin** [comment]
https://docs.google.com/spreadsheets/d/1vwBD--OUx2DJVgsHA-564SghOdhUlUHO-5_sFbVj4pY/edit?usp=sharing 
https://docs.google.com/spreadsheets/d/1xzPblmtsB1FuUV4PMt8okhEFG6Q9ltZRALPZAh_4U_M/edit?usp=sharing 
can you try again ?

**Comment by jpfeuffer** [comment]
How did you calculate the difference? Did you check for a non-zero "study_variable_abundance" in the PEP section and compared it with the rows in the msstats output that have the same "Reference" file?
