### ISSUE TITLE
Improving the report from PTX 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#22]
PTX is quite good for generating reports of MQ, we hope to get some ideas from there. The following metrics and styles will be good to be implemented: 

- [ ] The `Show Help` button: a collapsable button that shows a minor description of the metric. (Figure 1). This can help the new users to understand the QC report and the metrics we are computing. 
- [ ] The heatmap plot of general metrics for each mzML is quite nice and robust (Figure 2). These metrics can be computed with the [qccalculator tool](https://github.com/bigbio/qccalculator). The idea here is to have a list of metrics per mzML and then compute the heatmap. 
- [ ] I think, we should add a section with corresponding subsections where we explore for each mzML file the corresponding metrics see in the repo from 1.3.11 - 1.3.14, 1.3.18, 1.3.19, 1.3.25,  

Figure 1: 

![Screen Shot 2021-04-22 at 14 41 31](https://user-images.githubusercontent.com/52113/115724557-f5318b80-a378-11eb-9a8d-c13ff3d0463f.png)

Figure 2: 

![image](https://user-images.githubusercontent.com/52113/115724916-48a3d980-a379-11eb-84fc-1f0d16f4ade3.png)

**Comment by daichengxin** [comment]
Hi Yasset, I tested the qccalculator tool. But I found that most of the heat map metrics are not calculated in the tool. Can you check again ?

**Comment by daichengxin** [comment]
- [ ] Heatmap score [EVD: Contaminants] I don’t understand how this score is calculated, and I can’t find it in the qccalculator  tool.
- [ ] Heatmap score [MSMS: MC]: the fraction (0% - 100%) of fully cleaved peptides per Raw file.  I am not sure 
- [ ] Heatmap score [MSMS: MC Var]: each Raw file is scored for its deviation (score: MedianDist) from the ‘average’ digestion state of the current study. Missing. 
- [ ] Heatmap score [EVD: Charge]: Deviation of the charge 2 proportion from a representative Raw file
- [ ] Heatmap score [MS2 Scans: TopN high]: rewards if TopN was reached on a regular basis. Missing
- [ ] Heatmap score [MS2 Scans: TopN over RT]: Rewards uniform (function Uniform) TopN events over time. Missing
- [ ] Heatmap score [EVD: ID rate over RT]: Scored using ‘Uniform’ scoring function.  It seems that we need to look at the source code of this report.
- [ ] Heatmap score [EVD: RT Peak Width]: Scored using BestKS function, i.e. the D statistic of a Kolmogoriv-Smirnoff test. It seems that we also need to look at the source code of this report.
- [ ] Heatmap score [EVD: MBR Align]: fraction of ‘green’ vs. ‘green+red’ peptides. 
- [ ] Heatmap score [EVD: MBR ID-Transfer]
- [ ] Heatmap score [MS2 Scans: Ion Inj Time]: Linear score as fraction of MS/MS below the threshold. Note that this threshold needs customization depending on the instrument used (e.g., ITMS vs. FTMS). Where can I extract this information？
- [ ] Heatmap score [MS2 Scans: Intensity]: Linear score (0-100%) between 3 < (TIC / base peak) < 10. we score the ratio BP * 10 > TIC (this would be 100% score). If it’s only BP * 3 < TIC, we say this MS/MS failed (0%). Anything between 3x and 10x gets a score in between. The score for the Raw file is computed as the median score across all its MS/MS scans.  I did not find this metric in the qccalculator tool.
- [ ] Heatmap score [EVD: MS2 Oversampling]: The percentage of non-oversampled 3D-peaks. Missing
- [ ] Heatmap score [EVD: MS Cal Pre (20.0)]: the centeredness (function CenteredRef) of uncalibrated masses in relation to the search window size. Missing.  It seems that we need to look at the source code of this report.
- [ ] Heatmap score [EVD: MS Cal-Post]: The variance and centeredness around zero of the calibrated distribution (function GaussDev). Missing
- [ ] Heatmap score [MSMS: MS2 Cal (Analyzer)]: rewards centeredness around 0 ppm/Da (function Centered). Missing
- [ ] Heatmap score [MS2 Scans: TopN ID over N]: Rewards uniform identification performance across all scan events. I did't understand this. 
- [ ] Heatmap score [EVD: Pep Missing]: Linear scale of the fraction of missing peptides.  I did't find this metric in the qccalculator tool.
