### ISSUE TITLE
Distribution of precursor charges 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#3]
short description:  This is a bar chart representing the distribution of the precursor ion charges for a given whole experiment. This information can be used to identify potential ionization problems including many 1+ charges from an ESI ionization source or an unexpected distribution of charges. MALDI experiments are expected to contain almost exclusively 1+ charged ions. An unexpected charge distribution may furthermore be caused by specific search engine parameter settings such as limiting the search to specific ion charges.

![image](https://user-images.githubusercontent.com/52113/111085572-cf120380-850f-11eb-8bd1-9b4fa113ef2b.png)

**Comment by daichengxin** [comment]
#13
