### ISSUE TITLE
Performance plot

### ISSUE THREAD

**Issue by timosachsenberg** [bigbio/pmultiqc#34]
Awesome tool.
One suggestion:
The performance overview plot is hard to read with the scaling from 0 to 1?
Could this keep the original values and only adapt the color palette?
![image](https://user-images.githubusercontent.com/5803621/144300671-e8dde77e-99b9-4b8d-8818-1cb937546223.png)

**Comment by daichengxin** [comment]
Thanks. I can try it to make it more readable. And this tool needs some improvements, I’m working on it @timosachsenberg

**Comment by jpfeuffer** [comment]
I don't think keeping the original values makes sense. You will want to compare at least across one metric. If they have vastly different scales this won't work at all.
