### ISSUE TITLE
Meaning of "Contaminants" metric in "Performance Overview" heatmap?

### ISSUE THREAD

**Issue by hendrikweisser** [bigbio/pmultiqc#38]
At the start of the MultiQC/quantms report, the first column in the "Performance Overview" heatmap shows the "Contaminants" metric. The documentation ("Help" button) only says:
> Heatmap score[Contaminants]: as fraction of summed intensity with 0 = sample full of contaminants; 1 = no contaminants

What is considered a contaminant? What intensities are summed?
Wouldn't it be more intuitive to use 0 for "no contaminants" and 1 for "all contaminants"?

**Comment by daichengxin** [comment]
1 - Sum(decoy peptides intensity) / total intensity per file. To be consistent with the other scores, the higher the score the better in the heatmap

**Comment by hendrikweisser** [comment]
> 1 - Sum(decoy peptides intensity) / total intensity

Hm, but decoys and contaminants are different things. Contaminants may be actually present in the sample (just not biologically relevant), while decoys are not expected to occur. Decoy hits are only relevant for scoring and are usually filtered out during the analysis. Tracking the level of contamination in a sample would be really useful for QC, but I don't think it can be done based on decoy annotations.

**Comment by daichengxin** [comment]
Got it. will fix. Thanks a lot

**Comment by daichengxin** [comment]
fixed. #43
