### ISSUE TITLE
Peaks per MS2 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#4]
short description: This chart represents a histogram containing the number of peaks per MS/MS spectrum in a given experiment. This chart assumes centroid data. Too few peaks can identify poor fragmentation or a detector fault, as opposed to a large number of peaks representing very noisy spectra. This chart is extensively dependent on the pre-processing steps performed to the spectra (centroiding, deconvolution, peak picking approach, etc). The example shown in Figure 7 shows that poor quality spectra are more likely to be decoy identifications that target identifications.

![image](https://user-images.githubusercontent.com/52113/111085596-f072ef80-850f-11eb-841d-93f5ca96784d.png)

**Comment by daichengxin** [comment]
#13
