### ISSUE TITLE
Peaks intensity distribution

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#5]
short description: This is a histogram representing the ion intensity vs. the frequency for all MS2 spectra in a whole given experiment (Figure 8). It is possible to filter the information for all, identified and unidentified spectra. This plot can give a general estimation of the noise level of the spectra. Generally, one should expect to have a high number of low intensity noise peaks with a low number of high intensity signal peaks. A disproportionate number of high signal peaks may indicate heavy spectrum pre-filtering or potential experimental problems. In the case of data reuse this plot can be useful in identifying the requirement for pre-processing of the spectra prior to any downstream analysis. The quality of the identifications is not linked to this data as most search engines perform internal spectrum pre-processing before matching the spectra. Thus, the spectra reported are not necessarily pre-processed since the search engine may have applied the pre-processing step internally. This pre-processing is not necessarily reported in the experimental metadata.

![image](https://user-images.githubusercontent.com/52113/111085637-16988f80-8510-11eb-832a-aedbdb0967dd.png)

**Comment by daichengxin** [comment]
#11
