### ISSUE TITLE
pmultiqc is not working the search peptides

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#53]
I have tried to search peptides in this pmultiqc report http://ftp.pride.ebi.ac.uk/pride/data/proteomes/proteogenomics/benchmakrs/PXD000279/pmultiqc/multiqc_report.html and is not working.

**Comment by jpfeuffer** [comment]
Your html still has the old JS files. Not sure what happened there but it is look for proteomicslfq.db and not the new quantms.db

**Comment by ypriverol** [comment]
Related with #54
