### ISSUE TITLE
Refactoring of quantification tables 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#54]
@WangHong007 @daichengxin we have decided to change the peptide tables in the pmultiqc to be compatible with both the DIA and DDA pipelines. Here, the original issue in quantms https://github.com/bigbio/quantms/issues/192

**Comment by daichengxin** [comment]
there is a big problem with cross-domain requests when request SQLite .db file due to the browser's security setting. Users need to set --disable-web-security in their browser or they can't get sqlite data. So they can't query and other operations

**Comment by ypriverol** [comment]
I think is ok. We can make that clear in the documentation
