### ISSUE TITLE
Add search engine score summaries

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/pmultiqc#62]
Based on idXMLs.

Histograms per search engine:
 - one series per file
 - always targets (dark color) and decoys (light color)
 - use e.g. specEvalue for MSGF and xcorr for comet

Histogram per file (e.g. dropdown menu) or histogram after merging
 - one series per search engine, after Percolator/IDPEP
 - always targets (dark color) and decoys (light color)
 - use PEP or PP as score

Either: Barplot on number of matching search engine IDs per PSM
Or: Scatterplot of number of matching search engine IDs per PSM versus the best PEP/PP score

**Comment by WangHong007** [comment]
Hi Julianus! @jpfeuffer An example is here: [pmultiqc/multiqc_report.html](https://github.com/WangHong007/Data-Folder/blob/b6c939c4306916082334bb5b4d451931bb967e4d/pmultiqc/multiqc_report.html)

1. **Search scores summary plot**

- Using mean `Comet xcorr` or `MSGF SpecEvalue` (the mean of each file)
![图片](https://user-images.githubusercontent.com/88552471/178641320-83d771b2-4f4e-44ab-afd3-c58abb04f68d.png)

2. **PEPs summary plot**

- Using the mean of `PEPs` for both search engines (the mean of all the files)
![图片](https://user-images.githubusercontent.com/88552471/178641943-75797b93-2123-40db-9f60-570fb88caf49.png)

3. **Identified PSMs number plot**
![图片](https://user-images.githubusercontent.com/88552471/178642238-732b02ea-79ef-4c97-b196-748f87260337.png)

Question:
> Barplot on number of matching search engine IDs per PSM

I haven't found any PSM quantitative information in idXMLs yet. Does this need to be counted manually? If so, which part of information should be counted, for example, the frequency of sequence in PeptideHits?

**Comment by jpfeuffer** [comment]
Hi! Thanks a lot, that is a good start.

1) How hard would it be to do a Histogram, as we did for most of the other diagrams. I think the mean is too uninformative. Maybe we could have the files for selection up there (where Comet and MSGF are now). And then have different plots for the search engines.

2) Same comment.

3) Here I meant more the agreement over different search engines. This could be done by checking the "support" metavalue in the idXML after consensusID. Again, a histogram would be better.

**Comment by WangHong007** [comment]
Got it, I will also give an example when I finish it

**Comment by WangHong007** [comment]
Hi Julianus! One more thing to confirm is whether you want to use the Histogram class to quantify and plot different ranges of search scores and PEPs, since its current function is to quantify and plot data from specific ranges or values. In addition, ploting the search score or PEP for each PSM results in `flat images` where toolbox functions are disabled.

**Comment by jpfeuffer** [comment]
Hi! Yes, the histogram should support arbitrary ranges with start value, end value and number of bins.
Flat imageare ok for now.

**Comment by WangHong007** [comment]
A new example is here: [pmultiqc/multiqc_report_6.html](https://github.com/WangHong007/Data-Folder/blob/ff5e620321c59a1aa69251c24980a8bffa0f1bbc/pmultiqc/multiqc_report_6.html)
Three sections as follow:
![图片](https://user-images.githubusercontent.com/88552471/179353383-78276829-68f0-4f61-8c71-cd30d5a71f6a.png)
![图片](https://user-images.githubusercontent.com/88552471/179353391-44a18e8f-4715-49c6-aece-081748dbf9dd.png)
![图片](https://user-images.githubusercontent.com/88552471/179353395-bede5544-fcfe-4285-a454-f3a9cb286098.png)
So far I haven't found any examples of using multiQC to draw histograms, only bar graphs; The current Histogram class is also used to draw bar graphs.
The range of search scores and PEPs is temporarily `start=0, end=1, step=0.2`

**Comment by jpfeuffer** [comment]
Hi. I think a histogram is basically a bar graph. So that's fine.
I would just use much more bins (around 100?). That means just decrease the step size. And maybe we can reduce the space between the bars a little bit. Such that they are bit closer to each other. Maybe that happens automatically if we increase the number of bins.

**Comment by WangHong007** [comment]
Hi Julianus! The step size I adopted was 0.02, because 100 bars would lead to flat images, and they could not reflect the quantity information. Then I stacked the bars so that they looked closer together.
An example: [pmultiqc/multiqc_report.html](https://github.com/WangHong007/Data-Folder/blob/83c534fa9a68edee4a3e6c8bdb754312792d9955/pmultiqc/multiqc_report_4.html)

Three sections as follow:
![图片](https://user-images.githubusercontent.com/88552471/179382333-f3ab9706-6767-436d-a60e-6525aef2f4a8.png)
![图片](https://user-images.githubusercontent.com/88552471/179382341-6b59f752-382a-4ad4-82bc-032cf98291ca.png)
![图片](https://user-images.githubusercontent.com/88552471/179382345-72b08494-b4a4-4e1d-9454-d9ff511cc2dc.png)

**Comment by jpfeuffer** [comment]
Yes this is better. I think stacking is fine. But I think you need to adapt start and end for Xcorr and SpecEvalue. For SpecEvalue probably -log10(SpecEvalue) is better as a value.
They can have much broader ranges than 0-1.

**Comment by WangHong007** [comment]
Got it.

**Comment by WangHong007** [comment]
Hi Julianus! A new Example is here: [report](https://github.com/WangHong007/Data-Folder/blob/f9cc5f31270b3197a8ebfc9f38b26c73ea9e841a/pmultiqc/multiqc_report_9.html)
In this section, I use -lg(SpecEvalue) for MSGF+ and |xcorr| for Comet. The range of -lg(SpecEvalue) is `start=-1, end=inf, step=0.1`. The new bar plot as follow:
![图片](https://user-images.githubusercontent.com/88552471/180639265-f195e335-a2ff-4501-8c29-b74cec93a43e.png)
Do I need to remove the first few empty bars (SpecEvalue >= 10) in the plot like this:
![图片](https://user-images.githubusercontent.com/88552471/180639750-2a7dcdc3-1466-4a89-b642-5e04b2227256.png)

**Comment by jpfeuffer** [comment]
Nice. But I kind of thought about adapting the end in the sense that the bins would then cover a larger range.
What is the maximum value of the respective scores.
It does not make sense to show a huge bar for the last bin.

**Comment by WangHong007** [comment]
Xcorr has a range greater than 0, and an example of his histogram is as follows:
![图片](https://user-images.githubusercontent.com/88552471/180904886-e4632765-8d48-4315-9008-6825420cb02a.png)
I use the range `start=0, end=5, step=0.1` and the result is as follows:
![图片](https://user-images.githubusercontent.com/88552471/180905729-66e2cf6d-4481-4ff4-8a3c-cf9a8b0c14f9.png)

SpecEvalue has a range of 0 to 1, and its negative logarithm has a range of 0 to infinity. I use the range `start=0, end=inf, step=0.4`, and the results are as follows:
![图片](https://user-images.githubusercontent.com/88552471/180906452-f456f951-d75f-4ad5-9497-cd031175e44f.png)

**Comment by jpfeuffer** [comment]
Hi! That looks fine for a start. Maybe we have to adjust the ranges later, after we saw some more data. You have to make sure that it is very easily edited. Maybe with a global constant variable in the module.
e.g. `XCORR_HIST_RANGE = (x,y)`

**Comment by jpfeuffer** [comment]
Other than that, can you upload a full report somewhere?

**Comment by ypriverol** [comment]
@WangHong007 I think you can make a proper PR that includes the examples of generation of the reports with the new changes.

**Comment by WangHong007** [comment]
New example is here: [report](https://github.com/WangHong007/Data-Folder/blob/25789cb868dfb17d2900c5c35756c9a2471f1807/pmultiqc/multiqc_report_19.html)
A global constant variable will be added. BTW, the `Histogram` class need to be modified to adapt these changes.

**Comment by WangHong007** [comment]
@ypriverol Got it.

**Comment by jpfeuffer** [comment]
By the way, by which logic did you do the consensus PSMs?

I think it is better if we call it:
Number of agreeing search engines per PSM

And then just list the numbers : 1 or 2 (or in the future 3 or 4)

**Comment by jpfeuffer** [comment]
I can see it when you open the PR
