### ISSUE TITLE
Move parsing of mzML to a step in the workflow

### ISSUE THREAD

**Issue by jpfeuffer** [bigbio/pmultiqc#63]
It just takes too long during multiqc execution.
Could be done in the mzML indexing step. You can write out a table:

spec_id, peaks, base int, ...

**Comment by WangHong007** [comment]
An example is here: [mzml_dataframe_file_part](https://github.com/WangHong007/Data-Folder/blob/f9cc5f31270b3197a8ebfc9f38b26c73ea9e841a/quantms/mzml_statistics.csv)
I extracted information about MS1, MS2, MS3 (if exist) from mzMLs, where MS1 and MS3 only have information about whether they exist or not.
What is done is to collect all mzMLs and extract information to make a dataframe, without statistics. The final csv file is passed to pmultiqc for processing.

**Comment by jpfeuffer** [comment]
Wouldn't it be smarter to have a column MSlevel that then has the values 1,2,3,... ?
