### ISSUE TITLE
Final number of peptides for mzTab 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#7]
In this table would be great to have the final number of peptides. Apart of the Comet and MSGF+ would be great to have the final number for the results, the mzTab. 

![Screen Shot 2021-03-14 at 22 05 09](https://user-images.githubusercontent.com/52113/111085926-89eed100-8511-11eb-9e41-a7c40c6d6974.png)

**Comment by daichengxin** [comment]
#11
