### ISSUE TITLE
Some metrics to be included 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#8]
Some metrics to be included in the library that can help the understanding of the experiment. 

https://jiahaoh.com/project/qcreport.html

**Comment by ypriverol** [comment]
Another example from CPTAC, here https://cptc-xfer.uis.georgetown.edu/publicData/Phase_III_Data/Reproducible_Workflow_for_MS_Mertins/CPTAC_S036_Proteome_CDAP_Protein_Report.r1/CPTAC3_Harmonization_PhaseII_Proteome.qcmetrics.html

**Comment by daichengxin** [comment]
#11
