### ISSUE TITLE
movement from 1.19 -> 1.23 multiqc

### ISSUE THREAD

**Issue by ypriverol** [bigbio/pmultiqc#98]
The movement from 1.19 -> 1.23 introduces some challenges. 

- [x] Bug, I have to disable the PEP plot because of an error in the plot. 
- [ ] The section with multiple plots with search engine scores had to be put in multiple sections because `xcorr_bar_html + SpecE_bar_html + hyper_bar_html` is not available. Would be great to have all plots combined. 
- [x] Multiple warnings are happening: 
```
        validation | quantms/quantms.py: Warnings in Category plot configuration {'name': '1', 'description': 'MS/MS counts per 3D-peak is 1'}:
        validation | • unrecognized field 'description'. Available fields: name, color
        validation | quantms/quantms.py: Warnings in Category plot configuration {'name': '2', 'description': 'MS/MS counts per 3D-peak is 2'}:
        validation | • unrecognized field 'description'. Available fields: name, color
        validation | quantms/quantms.py: Warnings in Category plot configuration {'name': '>= 3', 'description': 'MS/MS counts per 3D-peak >= 3'}:
        validation | • unrecognized field 'description'. Available fields: name, color
    custom_content | nf-core-quantms-methods-description: Found 1 sample (HTML)
    custom_content | nf-core-quantms-summary: Found 1 sample (HTML)
```
- [x] the peptides and proteins tables for searching are not working for this given example -> 
[e4d11f9c314590c8e0368bf06500d0.zip](https://github.com/user-attachments/files/16447687/e4d11f9c314590c8e0368bf06500d0.zip)
. I had to update the multiqc configuration file @daichengxin attached also here [multiqc_config.yml.zip](https://github.com/user-attachments/files/16447668/multiqc_config.yml.zip)

@daichengxin can you help me to fix some of these small issues.

**Comment by daichengxin** [comment]
For the second point, Are you want to split the SEARCH ENGINE SCORE into multiple sections or others? ![image](https://github.com/user-attachments/assets/9479b190-8bd0-4ab7-823a-fe52ab1d4682). I didn't get.
